const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto');
const {diagnosticEntries,redactNote}=require('../electron/diagnostics.cjs'),{endpointUrl,payloadForFeedback,createFeedbackClient,validateReceipt}=require('../electron/feedback.cjs'),{createFeedbackServer}=require('../support/feedback-server.cjs');
const input=()=>({requestId:crypto.randomUUID(),kind:'bug',category:'resume',message:'点击更新后没有继续解析',includeLogs:true});
const payload=()=>payloadForFeedback(input(),{version:'0.5.20',platform:'win32',entries:[{ts:'2026-10-03 10:00:00',level:'error',msg:'真实姓名 private-password JD resume error',meta:{phone:'13800138000',token:'private-token',company:'jd',count:3,code:'ETIMEDOUT'}}]});
const temp=()=>fs.mkdtempSync(path.join(os.tmpdir(),'yjt-feedback-'));
test('shared logs discard all free text/stacks/private metadata',()=>{const safe=diagnosticEntries([{ts:'private-time',level:'error',msg:'姓名 private-password',meta:{error:'private-stack',url:'https://private/?key=private-key',name:'个人',count:4,company:'jd',code:'ETIMEDOUT'} }]);assert.doesNotMatch(JSON.stringify(safe),/private|个人|姓名|password|key=/);assert.equal(safe[0].meta.count,4);assert.equal(safe[0].meta.code,'ETIMEDOUT');});
test('diagnostic sanitizer is idempotent and bounded',()=>{const xs=diagnosticEntries(Array.from({length:80},()=>({level:'warn',msg:'resume error',meta:{count:1}})));assert.equal(xs.length,50);assert.deepEqual(diagnosticEntries(xs),xs);});
test('notes strip credentials/contact URLs/paths, not the useful issue statement',()=>{const x=redactNote('简历上传后卡住 me@example.com 13800138000 320123199001011234 token=privatetoken https://secret.test/?key=secret C:\\Users\\private\\resume.pdf');assert.match(x,/简历上传后卡住/);assert.doesNotMatch(x,/me@example|13800138000|320123199001011234|privatetoken|secret.test|Users/);});
test('endpoint accepts HTTPS or explicit loopback HTTP, rejects credential/query paths',()=>{assert.equal(endpointUrl('https://feedback.example/v1/feedback').protocol,'https:');assert.equal(endpointUrl('http://127.0.0.1:8096/v1/feedback').protocol,'http:');for(const url of ['http://remote.example/v1/feedback','https://u:p@example/v1/feedback','https://example/v1/feedback?key=secret','https://example/other'])assert.throws(()=>endpointUrl(url));});
test('payload uses runtime version and default structural logs; opt-out sends none',()=>{const p=payload();assert.equal(p.version,'0.5.20');assert.equal(p.logs.schema,1);assert.doesNotMatch(JSON.stringify(p.logs),/private|13800138000/);assert.equal(payloadForFeedback({...input(),includeLogs:false},{version:'0.5.20'}).logs,null);assert.throws(()=>payloadForFeedback({...input(),message:''},{version:'0.5.20'}));});
test('receipt must acknowledge exact ID, sent status and same-origin log token URL',()=>{const id=crypto.randomUUID(),e=endpointUrl('https://feedback.example/v1/feedback');assert.equal(validateReceipt({status:200,body:{ok:true,requestId:id,status:'sent'}},id,e).ok,true);assert.equal(validateReceipt({status:200,body:{ok:true,requestId:'wrong',status:'sent'}},id,e),null);assert.throws(()=>validateReceipt({status:200,body:{ok:true,requestId:id,status:'sent',logUrl:'https://other.example/diagnostics/'+('a'.repeat(64))+'.txt'}},id,e));});
test('unknown network result is durable, blocks new sends and can be receipt-checked',async()=>{
 const file=path.join(temp(),'outbox.json'),p=payload();let sends=0;const first=createFeedbackClient({file,transport:async()=>{sends++;throw Error('timeout');}});assert.equal((await first.send('http://127.0.0.1:8096/v1/feedback',p)).code,'delivery-unknown');
 const next=createFeedbackClient({file,transport:async(_url,_p,options)=>{assert.equal(options.method,'GET');return{status:200,body:{ok:true,status:'sent',requestId:p.requestId}};}});assert.equal((await next.send('http://127.0.0.1:8096/v1/feedback',payload())).code,'delivery-unknown');assert.equal((await next.check(p.requestId)).ok,true);assert.equal(sends,1);
});
test('confirmed duplicate send returns stored receipt without second delivery',async()=>{let count=0;const p=payload(),client=createFeedbackClient({transport:async()=>{count++;return{status:200,body:{ok:true,status:'sent',requestId:p.requestId}};}});assert.equal((await client.send('https://feedback.example/v1/feedback',p)).ok,true);assert.equal((await client.send('https://feedback.example/v1/feedback',p)).ok,true);assert.equal(count,1);assert.equal((await client.send('https://feedback.example/v1/feedback',{...p,message:'changed'})).code,'feedback-id-conflict');});
test('broken outbox is preserved and cannot cause another delivery',async()=>{const file=path.join(temp(),'outbox.json');fs.writeFileSync(file,'broken');let count=0;const c=createFeedbackClient({file,transport:async()=>{count++;}});assert.equal((await c.send('https://feedback.example/v1/feedback',payload())).code,'feedback-outbox-invalid');assert.equal(fs.readFileSync(file,'utf8'),'broken');assert.equal(count,0);});
async function fixture(t,notify,extra={}){const server=createFeedbackServer({dataDir:temp(),publicBaseUrl:'http://127.0.0.1:8096/',allowLocal:true,notify,maxPerMinute:1000,...extra});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));return{server,url:'http://127.0.0.1:'+server.address().port};}
test('real HTTP relay acks after notify, sanitizes log endpoint and deduplicates',async t=>{const sent=[],f=await fixture(t,async text=>{sent.push(text);return{sent:true};}),p=payload();p.logs.entries.push({level:'error',msg:'untrusted raw PII',meta:{token:'private-key'}});const post=()=>fetch(f.url+'/v1/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)}).then(r=>r.json());const first=await post(),again=await post();assert.equal(first.ok,true);assert.deepEqual(again,first);assert.equal(sent.length,1);assert.match(sent[0],/版本：0.5.20/);const parsed=new URL(first.logUrl),r=await fetch(f.url+parsed.pathname);assert.equal(r.status,200);assert.doesNotMatch(await r.text(),/private|untrusted|PII|13800138000/);assert.equal(r.headers.get('x-content-type-options'),'nosniff');});
test('relay does not invent delivery success on false or unknown notify',async t=>{const failed=await fixture(t,async()=>({sent:false})),unknown=await fixture(t,async()=>{throw Error('timeout');});for(const [f,status]of [[failed,'failed'],[unknown,'unknown']]){const p=payload(),r=await fetch(f.url+'/v1/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const body=await r.json();assert.equal(body.ok,false);assert.equal(body.status,status);const checked=await fetch(f.url+'/v1/feedback/'+p.requestId).then(r=>r.json());assert.equal(checked.status,status);}});
test('parallel duplicate requests send at most one notification',async t=>{let release,count=0;const gate=new Promise(r=>release=r),f=await fixture(t,async()=>{count++;await gate;return{sent:true};}),p=payload(),send=()=>fetch(f.url+'/v1/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)}).then(r=>r.json());const first=send();while(count===0)await new Promise(r=>setTimeout(r,5));const second=await send();assert.equal(second.status,'sending');release();assert.equal((await first).ok,true);assert.equal(count,1);});
test('log token expires and invalid JSON/body size is rejected',async t=>{let now=0;const f=await fixture(t,async()=>({sent:true}),{clock:()=>now,ttlMs:50}),p=payload();const body=await fetch(f.url+'/v1/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)}).then(r=>r.json());now=51;assert.equal((await fetch(f.url+new URL(body.logUrl).pathname)).status,410);assert.equal((await fetch(f.url+'/v1/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:'{' })).status,400);assert.equal((await fetch(f.url+'/v1/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:'x'.repeat(40000)})).status,413);});
