const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');
const root=process.env.FIXTURE_SOURCE_ROOT||path.resolve(__dirname,'..'),entry='https://qq.jd.com/new/wx/login.action?ReturnUrl=fixture',callback='https://qq.jd.com/new/wx/callback.action?code=fixture';
function make(){const {createJdAuthStatus}=require(path.join(root,'electron/jd-auth-status.cjs'));let clock=0;const m=createJdAuthStatus({now:()=>clock,scanWaitMs:300000,callbackTimeoutMs:30000});return{m,setTime:n=>clock=n};}
const anonymous={isCampus:true,resumeSection:true,loginVisible:true,hasAuthCookie:false},signed={...anonymous,loginVisible:false,hasAuthCookie:true};
test('JD no result starts pending, not authenticated',()=>{const {m}=make();assert.equal(m.snapshot().state,'pending');m.update(anonymous);assert.equal(m.snapshot().state,'pending');});
test('JD valid QR waits and long wait asks refresh without declaring official expiry',()=>{const {m,setTime}=make();m.observe(entry);assert.equal(m.snapshot().state,'awaiting-scan');setTime(300000);m.update(anonymous);assert.equal(m.snapshot().state,'stale');assert.equal(m.snapshot().code,'SCAN_WAIT_TOO_LONG');assert.doesNotMatch(m.snapshot().message,/已过期|已失效/);});
test('JD callback plus anonymous official page produces explicit failure',()=>{const {m,setTime}=make();m.observe(entry);m.observe(callback);assert.equal(m.snapshot().state,'checking');setTime(30000);m.update(anonymous);assert.equal(m.snapshot().state,'failed');assert.equal(m.snapshot().code,'CALLBACK_NO_AUTH');});
test('JD return route without real credential is never success',()=>{const {m,setTime}=make();m.observe(entry);m.observe(callback);m.observe('https://campus.jd.com/#/login-callback');setTime(30000);m.update({...anonymous,loginVisible:false,hasAuthCookie:false});assert.notEqual(m.snapshot().state,'verified');});
test('JD identity cookie is not required but authenticated UI and auth credential both are',()=>{const {m}=make();m.update({...signed,hasAuthCookie:false});assert.notEqual(m.snapshot().state,'verified');m.update({...signed,loginVisible:true});assert.notEqual(m.snapshot().state,'verified');m.update(signed);assert.equal(m.snapshot().state,'verified');});
test('JD late but real result can verify after stale/failure without retrying',()=>{const {m,setTime}=make();m.observe(entry);setTime(400000);m.update(anonymous);m.observe(callback);setTime(440000);m.update(anonymous);assert.equal(m.snapshot().state,'failed');m.update(signed);assert.equal(m.snapshot().state,'verified');});
test('JD logout clears verified state, new entry resets previous failed attempt',()=>{const {m,setTime}=make();m.update(signed);m.update(anonymous);assert.equal(m.snapshot().state,'pending');m.observe(entry);m.observe(callback);setTime(30000);m.update(anonymous);assert.equal(m.snapshot().state,'failed');m.observe(entry);assert.equal(m.snapshot().state,'awaiting-scan');});
test('JD previously verified result clears on loading, unrelated route or lost credential',()=>{const {m}=make();for(const probe of [null,{...signed,isCampus:false},{...signed,hasAuthCookie:false}]){m.update(signed);assert.equal(m.snapshot().state,'verified');m.update(probe);assert.equal(m.snapshot().state,'pending');}});
test('JD unknown or loading page is timeout, not false authenticated or definitive rejection',()=>{const {m,setTime}=make();m.observe(entry);m.observe(callback);setTime(30000);m.update(null);assert.equal(m.snapshot().code,'AUTH_CHECK_TIMEOUT');});
test('JD status never exposes query code or fake host, duplicate callback does not extend timeout',()=>{const {m,setTime}=make();m.observe(entry);m.observe('https://qq.jd.com.evil.test/new/wx/callback.action?code=SECRET');assert.equal(m.snapshot().state,'awaiting-scan');m.observe(callback);setTime(29000);m.observe(callback);setTime(30000);m.update(anonymous);assert.equal(m.snapshot().state,'failed');assert.doesNotMatch(JSON.stringify(m.snapshot()),/code=|SECRET|ReturnUrl/);});
