'use strict';
const fs=require('fs'),path=require('path'),os=require('os'),crypto=require('crypto'),{spawn}=require('child_process'),{verifySlot,inside}=require('./package-files.cjs');
function dayInShanghai(now=new Date()){const ps=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now),get=t=>ps.find(p=>p.type===t).value;return`${get('year')}-${get('month')}-${get('day')}`;}
function locations(owner,env=process.env){const bootstrapRoot=fs.realpathSync(owner),id=crypto.createHash('sha256').update(bootstrapRoot).digest('hex').slice(0,16),raw=path.resolve(env.YJTD_STATE_DIR||path.join(os.homedir(),'.local','state','yijian-toudi-skill'),'updates',id),base=fs.existsSync(raw)?fs.realpathSync(raw):raw;return{bootstrapRoot,base,pointer:path.join(base,'current.json'),state:path.join(base,'state.json'),lock:path.join(base,'check.lock')};}
function resolveSnapshot(owner,env=process.env){const p=locations(owner,env),fallback={root:p.bootstrapRoot,version:JSON.parse(fs.readFileSync(path.join(p.bootstrapRoot,'version.json'),'utf8')).version,bootstrapRoot:p.bootstrapRoot,base:p.base};
 try{const m=JSON.parse(fs.readFileSync(p.pointer,'utf8'));if(m.schema!==1||!inside(path.join(p.base,'installations'),m.root)||fs.realpathSync(m.root)!==path.resolve(m.root))throw Error('pointer-invalid');const slot=verifySlot(m.root);if(slot.version!==m.version||slot.sha256!==m.sha256)throw Error('pointer-version-invalid');return{...fallback,root:m.root,version:m.version,sha256:m.sha256};}catch{return fallback;}
}
function childEnv(env){const keys=['PATH','Path','SystemRoot','WINDIR','COMSPEC','HOME','USERPROFILE','TMP','TEMP','LOCALAPPDATA','YJTD_STATE_DIR','YJTD_SKILL_REPO','YJTD_SKILL_CHANNEL','YJTD_SKILL_RELEASES_URL','YJTD_SKILL_TEST_LOCAL'];return Object.fromEntries(keys.filter(k=>typeof env[k]==='string').map(k=>[k,env[k]]));}
function kickoff(snapshot,{env=process.env,now=new Date(),spawnImpl=spawn}={}){if(env.YJTD_SKILL_AUTO_UPDATE==='0')return{started:false,reason:'disabled'};try{const p=locations(snapshot.bootstrapRoot,env);let state={};try{state=JSON.parse(fs.readFileSync(p.state,'utf8'));}catch{}if(state.lastAttemptDay===dayInShanghai(now))return{started:false,reason:'checked-today'};const child=spawnImpl(process.execPath,[path.join(snapshot.root,'scripts/update-worker.cjs'),'--owner',p.bootstrapRoot],{detached:true,stdio:'ignore',windowsHide:true,env:childEnv(env)});child.on('error',()=>{});child.unref();return{started:true};}catch{return{started:false,reason:'background-unavailable'};}}
module.exports={locations,resolveSnapshot,kickoff,childEnv,dayInShanghai};
