#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto'),{locations,resolveSnapshot,dayInShanghai}=require('./bootstrap.cjs'),{sourceConfig,validUrl,download,releaseFor,assetsFor,checksumFor,compare}=require('./release-source.cjs'),{sha,unpack,writeSlot}=require('./package-files.cjs');
function atomicJson(file,data){const tmp=file+'.'+crypto.randomUUID()+'.tmp';fs.writeFileSync(tmp,JSON.stringify(data),{flag:'wx',mode:0o600});fs.renameSync(tmp,file);}
function acquire(file){
 const token=crypto.randomUUID(),data={pid:process.pid,token,at:new Date().toISOString()};
 for(let attempt=0;attempt<2;attempt++){try{fs.writeFileSync(file,JSON.stringify(data),{flag:'wx',mode:0o600});return()=>{try{if(JSON.parse(fs.readFileSync(file,'utf8')).token===token)fs.unlinkSync(file);}catch{}};}catch(e){if(e.code!=='EEXIST')throw e;let old;try{old=JSON.parse(fs.readFileSync(file,'utf8'));if(!Number.isSafeInteger(old.pid)||old.pid<=0)throw Error('bad lock');}catch{return null;}try{process.kill(old.pid,0);return null;}catch(error){if(error.code!=='ESRCH')return null;fs.unlinkSync(file);}}}return null;
}
async function checkAndUpdate({owner=path.resolve(__dirname,'..'),env=process.env,now=new Date(),request=download,allowLocal=false,commit=atomicJson}={}){
 let p,releaseLock,state={},candidate=null;try{p=locations(owner,env);fs.mkdirSync(p.base,{recursive:true,mode:0o700});p=locations(owner,env);releaseLock=acquire(p.lock);if(!releaseLock)return{status:'locked'};try{state=JSON.parse(fs.readFileSync(p.state,'utf8'));}catch{}const day=dayInShanghai(now);if(state.lastAttemptDay===day)return{status:'checked-today'};
 const current=resolveSnapshot(p.bootstrapRoot,env);state={...state,lastAttemptDay:day,lastAttemptAt:now.toISOString(),status:'checking',currentVersion:current.version,workerPid:process.pid};atomicJson(p.state,state);const config=sourceConfig(env);validUrl(config.url,{allowLocal});
 const raw=await request(config.url,{maxBytes:1024*1024,allowLocal}),release=releaseFor(JSON.parse(raw),config);if(!release){state.status='no-release';atomicJson(p.state,state);return{status:state.status,current:current.version};}
 const latest=release.tag_name.replace(/^v/,''),comparison=compare(latest,current.version);if(comparison===null)throw Error('update-version-invalid');state.latestVersion=latest;if(comparison<=0){state.status=comparison===0?'up-to-date':'remote-older';atomicJson(p.state,state);return{status:state.status,current:current.version,latest};}
 const assets=assetsFor(release,config,{allowLocal}),sum=await request(assets.checksum.browser_download_url,{maxBytes:4096,allowLocal,origin:assets.origin}),expected=checksumFor(sum,assets.name),buffer=await request(assets.archive.browser_download_url,{maxBytes:8*1024*1024,allowLocal,origin:assets.origin});
 if(sha(buffer)!==expected||(assets.archive.digest&&assets.archive.digest!=='sha256:'+expected)||(Number.isSafeInteger(assets.archive.size)&&assets.archive.size!==buffer.length))throw Error('update-archive-hash-size');
 const files=unpack(buffer,latest),root=writeSlot(p.base,files,latest,expected);candidate={root,version:latest,sha256:expected};commit(p.pointer,{schema:1,version:latest,root,sha256:expected,installedAt:now.toISOString()});state={...state,status:'updated',currentVersion:latest,lastSuccessAt:now.toISOString(),sha256:expected};atomicJson(p.state,state);return{status:'updated',previous:current.version,version:latest,sha256:expected};
 }catch(error){if(candidate&&p){const actual=resolveSnapshot(p.bootstrapRoot,env);if(actual.version===candidate.version&&actual.sha256===candidate.sha256)return{status:'updated',version:actual.version,stateRecorded:false};}if(p){try{atomicJson(p.state,{...state,status:'failed',errorCode:/^[a-z0-9-]+$/.test(error.message||'')?error.message:(error.code||'update-failed')});}catch{}}return{status:'failed',keptPrevious:true};}finally{releaseLock?.();}
}
if(require.main===module){const args=process.argv.slice(2),i=args.indexOf('--owner');checkAndUpdate({owner:i>=0?args[i+1]:undefined,allowLocal:process.env.YJTD_SKILL_TEST_LOCAL==='1'}).catch(()=>{});}
module.exports={checkAndUpdate,atomicJson,acquire};
